[features]
seeds = false
skip-lint = false
[programs.localnet]
klend = "KLend2g3cP87fffoy8q1mQqGKjrxjC8boSyAYavgmjD"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
